name: flutter_application
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- STATE MANAGEMENT & NAVIGASI ---
  get: ^4.6.6

  # --- UI & DESIGN ---
  google_fonts: ^6.1.0        # Biar fontnya modern
  carousel_slider: ^5.1.1     # Untuk Banner Promo (Home)
  intl: ^0.20.2               # Format Rupiah (Rp 10.000)

  # --- DATABASE (CLOUD & LOCAL) ---
  supabase_flutter: ^2.0.2    # Database Utama
  hive: ^2.2.3                # Database Lokal (Cache)
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2  # Simpan status Login sederhana

  # --- MAPS & LOKASI (MODUL 5) ---
  flutter_map: ^6.0.0         # Peta OpenStreetMap
  latlong2: ^0.9.0            # Koordinat
  geolocator: ^10.1.0         # GPS Hardware

  # --- NOTIFIKASI (MODUL 6) ---
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^17.2.1

  # --- LAINNYA ---
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6 
  
  # --- TAMBAHAN UNTUK GANTI LOGO ---
  flutter_launcher_icons: ^0.13.1

# Konfigurasi Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# --- KONFIGURASI LOGO APLIKASI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpg" # Pastikan file ini ada!
  min_sdk_android: 21